### ISSUE TITLE
Export failing

### ISSUE THREAD

**Issue by uded** [TablePress/TablePress#210]
While exporting data using wp-cli error is thrown:

```
# wp --allow-root export --max_file_size=100 --post_type=tablepress_table
Starting export process...
Writing to file data.wordpress.2024-12-02.000.xml
PHP Fatal error:  Uncaught Error: Call to undefined function wxr_cdata() in wp-content/plugins/tablepress/models/model-table.php:1243
Stack trace:
#0 /wp-includes/class-wp-hook.php(324): TablePress_Table_Model->add_table_id_to_wp_export()
#1 /wp-includes/plugin.php(205): WP_Hook->apply_filters()
#2 phar:///usr/local/bin/wp/vendor/wp-cli/export-command/src/WP_Export_Query.php(418): apply_filters()
#3 phar:///usr/local/bin/wp/vendor/wp-cli/export-command/src/WP_Export_Query.php(151): WP_Export_Query::get_meta_for_post()
#4 phar:///usr/local/bin/wp/vendor/wp-cli/export-command/src/WP_Map_Iterator.php(11): WP_Export_Query->exportify_post()
#5 [internal function]: WP_Map_Iterator->current()
#6 phar:///usr/local/bin/wp/vendor/wp-cli/export-command/src/WP_Export_Split_Files_Writer.php(56): IteratorIterator->rewind()
#7 phar:///usr/local/bin/wp/vendor/wp-cli/export-command/functions.php(16): WP_Export_Split_Files_Writer->export()
#8 phar:///usr/local/bin/wp/vendor/wp-cli/export-command/src/Export_Command.php(198): wp_export()
#9 [internal function]: Export_Command->__invoke()
#10 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(100): call_user_func()
#11 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}()
#12 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(497): call_user_func()
#13 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(441): WP_CLI\Dispatcher\Subcommand->invoke()
#14 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(464): WP_CLI\Runner->run_command()
#15 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1295): WP_CLI\Runner->run_command_and_exit()
#16 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#17 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(83): WP_CLI\Bootstrap\LaunchRunner->process()
#18 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
#19 phar:///usr/local/bin/wp/php/boot-phar.php(20): include('...')
#20 /usr/local/bin/wp(4): include('...')
#21 {main}
  thrown in wp-content/plugins/tablepress/models/model-table.php on line 1243
```

It seems this problem doesn't occur in the admin UI. But it's not practical for me to use it, as the export of my website is over 4GB...

**Comment by TobiasBg** [comment]
Hi @uded,

Thanks for letting me know about this! Indeed, it seems like the mentioned `wxr_cdata()` function is only loaded by WordPress when in the admin UI.
But I think that we can solve this by manually loading it as well, using the line
```php
require_once ABSPATH . 'wp-admin/includes/export.php';
```
before that line 1243 in the model-table.php.

Can you maybe try if that solves the problem?

Best wishes,
Tobias
